### ISSUE TITLE
[libretro] null pointer for core option

### ISSUE THREAD

**Issue by lab313ru** [ekeeke/Genesis-Plus-GX#234]
First, the GX core checks variables:
![default](https://user-images.githubusercontent.com/7189309/42411453-d8b35d32-8204-11e8-9fd1-8379b2413e84.png)

Then it requests variable's value in the libretro
![default](https://user-images.githubusercontent.com/7189309/42411562-a762b0b4-8206-11e8-860b-aa0ba56c376c.png)

The libretro returns false and then key value becomes NULL because there is no retro-core-options.cfg at this moment.
![default](https://user-images.githubusercontent.com/7189309/42411567-c02572b2-8206-11e8-8416-e0fadc19b083.png)
![default](https://user-images.githubusercontent.com/7189309/42411569-d484fc82-8206-11e8-9c66-57dca7090f22.png)

And now the GX core compares NULL value with a string, and it raises an exception.
![default](https://user-images.githubusercontent.com/7189309/42411577-0974ae4c-8207-11e8-905a-24f3d9b3860f.png)

You should add checks for that (for every variable).

**Comment by lab313ru** [comment]
My solution for this: https://github.com/ekeeke/Genesis-Plus-GX/pull/236
Fixed according to defaults options.

**Comment by ekeeke** [comment]
Indeed, probably do not happen very often but still not very safe to assume returned pointer is not null.

PR merged in https://github.com/ekeeke/Genesis-Plus-GX/commit/0ac750010ebdeb1f48e588855ea207d2b13fa2c9v
