### ISSUE TITLE
Still doesnt compile with latest devkitPPC version  

### ISSUE THREAD

**Issue by Ntemis** [ekeeke/Genesis-Plus-GX#260]
/media/demetris/c4487cfd-d71a-441b-b83d-23d8ce19475d/genesis-plus-gx/gx/main.c:381:25: error: 'S_IRWXU' undeclared (first use in this function)
     else mkdir(pathname,S_IRWXU);

**Comment by Ntemis** [comment]
after i put #include <sys/stat.h>  in /gx/main.c i got:
/media/demetris/c4487cfd-d71a-441b-b83d-23d8ce19475d/genesis-plus-gx/gx/gx_video.c:54:3: error: conflicting types for 'png_image'
 } png_image;
   ^~~~~~~~~
In file included from /media/demetris/c4487cfd-d71a-441b-b83d-23d8ce19475d/genesis-plus-gx/gx/gx_video.c:47:
/opt/devkitpro/portlibs/ppc/include/png.h:2739:3: note: previous declaration of 'png_image' was here
 } png_image, *png_imagep;
   ^~~~~~~~~
/opt/devkitpro/devkitPPC/base_rules:17: recipe for target 'gx_video.o' failed
make[1]: *** [gx_video.o] Error 1
Makefile.wii:109: recipe for target 'build_wii' failed

**Comment by ekeeke** [comment]
Looks like the version of libpng you are using is defining the same type name as the one used in gx_video.c: this was not the case in the version I have (not sure which version it is but I never updated it since there was no need for it) so you have two solutions: either use an older libpng version that does not have this type redefined or change the name of the type in gx_video.c (and the type of any variables using this type in gx_video.c)

PS: I will be interested by a PR with all your changes once you get it to compile with latest devkitppc, I personally still use r28 as I feel like there is zero benefits in updating (and even found out that latest gcc version being used produced less performant code than gcc 4.6.x or 4.8.x) but this might interest other people as older devkitppc versions do not seem to be available online anymore.

**Comment by ekeeke** [comment]
Fixed by
https://github.com/ekeeke/Genesis-Plus-GX/commit/3e1dcda9adc6b672dfb9b69b5962326cb22a7e77
https://github.com/ekeeke/Genesis-Plus-GX/commit/6ec124760fd90d586b6af7c0387c085d1d19db1e
https://github.com/ekeeke/Genesis-Plus-GX/commit/d927c6e4cbafdee302ab6f1edd4ae9f8f68678d8

I verified sourcecode compiles without any errors or warnings with devkitPPC r34 + libogc 1.8.21 + libfat 1.1.3 + libpng 1.6.34

**Comment by Ntemis** [comment]
Perfect will try in a few hours when i get home.
Thank you very much!

**Comment by Ntemis** [comment]
Sorry but i still get error
/home/demetris/Desktop/Genesis-Plus-GX/gx/gx_audio.c: In function 'gx_audio_Init':
/home/demetris/Desktop/Genesis-Plus-GX/gx/gx_audio.c:87:17: error: storage size of 'filestat' isn't known
     struct stat filestat;
                 ^~~~~~~~
/home/demetris/Desktop/Genesis-Plus-GX/gx/gx_audio.c:88:5: warning: implicit declaration of function 'stat'; did you mean 'mstats'? [-Wimplicit-function-declaration]
     stat(fname, &filestat);
     ^~~~
     mstats
/home/demetris/Desktop/Genesis-Plus-GX/gx/gx_audio.c:87:17: warning: unused variable 'filestat' [-Wunused-variable]
     struct stat filestat;
                 ^~~~~~~~
/opt/devkitpro/devkitPPC/base_rules:17: recipe for target 'gx_audio.o' failed
make[1]: *** [gx_audio.o] Error 1
Makefile.wii:109: recipe for target 'build_wii' failed
make: *** [build_wii] Error 2

**Comment by Ntemis** [comment]
Found this https://gbatemp.net/threads/frustrating-day-with-devkitpro.518985/
Look on last entry and it has the same error

**Comment by ekeeke** [comment]
That's weird because I don't get this error (I didn't get your initial error with main.c either with devkitppc r34 though). 

Adding also #include <sys/stat.h> in gx_audio.c should fix it but it should not have been necessary: in my include path, <sys/stat.h> is included by <sys/iosupport.h> which is itself included by <sys/dirent.h>, included itself by <dirent.h<, while <dirent.h> is included by <sys/dir.h, which is included by any Genesis Plus GX .c file through gx/osd.h file

Doesn't the same include path exist in your setup ? Are you sure devkitPPC is properly installed from the installer ? I did not use that pacman thing myself but the win32 auto-installer in an empty devkitpro directory so there should not be any differences.

**Comment by Ntemis** [comment]
Yes i have the latest tools from pacman with @Wintermute help so my install should be just fine.

**Comment by Ntemis** [comment]
btw your solution did fixed it but..then:
/home/demetris/Desktop/Genesis-Plus-GX/gx/fileio/file_load.c: In function 'LoadFile':
/home/demetris/Desktop/Genesis-Plus-GX/gx/fileio/file_load.c:342:17: error: storage size of 'filestat' isn't known
     struct stat filestat;
                 ^~~~~~~~
/home/demetris/Desktop/Genesis-Plus-GX/gx/fileio/file_load.c:343:8: warning: implicit declaration of function 'stat'; did you mean 'mstats'? [-Wimplicit-function-declaration]
     if(stat(filename, &filestat) != 0)
        ^~~~
        mstats
/home/demetris/Desktop/Genesis-Plus-GX/gx/fileio/file_load.c:342:17: warning: unused variable 'filestat' [-Wunused-variable]
     struct stat filestat;
                 ^~~~~~~~
/opt/devkitpro/devkitPPC/base_rules:17: recipe for target 'file_load.o' failed
make[1]: *** [file_load.o] Error 1
Makefile.wii:109: recipe for target 'build_wii' failed
make: *** [build_wii] Error 2

**Comment by Ntemis** [comment]
and i made it to the end
#include <sys/stat.h> was needed in:
gx_audio.c
file_load.c
and finally
file_slot.c
After those changes Genesis-Plus-GX was compiled ok with latest devkitpro on Ubuntu Bionic

**Comment by ekeeke** [comment]
It's obviously the same error, that file will be missing in every other .c files that use this stat type. A better solution would probably to add #include <sys/stat.h> in gx/osd.h

That said, I'm really curious as to why I don't get the error myself. Could you please look at your install path and see if the .h files I quoted above are there and include the aforementioned files ?

More exactly:
\devkitPro\devkitPPC\powerpc-eabi\include\sys\dir.h should have #include <dirent.h>
\devkitPro\devkitPPC\powerpc-eabi\include\dirent.h should have #include <sys/dirent.h>
\devkitPro\devkitPPC\powerpc-eabi\include\sys\dirent.h should have #include <sys/iosupport.h>
\devkitPro\devkitPPC\powerpc-eabi\include\sys\iosupport.h should have #include <sys/stat.h>

Is that the case for you ?

**Comment by Ntemis** [comment]
powerpc-eabi\include\sys\dirent.h  has only 
#include <sys/types.h>
#include <sys/syslimits.h>
all others you stated are ok

**Comment by Ntemis** [comment]
do you want me to input #include <sys/iosupport.h> in powerpc-eabi\include\sys\dirent.h and reset hard the 3 changes i made to the git and try to compile again?

**Comment by ekeeke** [comment]
That's not needed, result would be the same. I only wanted to know why it compiled fine for me and not for you and this is indeed the difference.
Now, I don't know why your sys/dirent.h is missing this line because it should definitively be there, see https://github.com/devkitPro/buildscripts/blob/master/dkppc/patches/newlib-3.0.0.patch#L7422
Weird stuff, as I said, and not something I want to spend much time on considering how boring and pointless these newlib issues are to me  (sometime it looks like some people are having fun constantly reworking perfectly working things just for the sake of changing things)

Anyway, there is no harm in including directly <sys/stat.h>, I will add it later just to be safe in case this changes again in next devkitppc version

**Comment by Ntemis** [comment]
@WinterMute any ideas why this?

**Comment by ekeeke** [comment]
Looks like you are not using the latest version of devkitPPC (r34) but are still using r32, r33 or an intermediate version.

Indeed, this is the commit which removed <sys/iosupport.h> inclusion from <sys/dirent.h>:
https://github.com/devkitPro/buildscripts/commit/df5a8f947a9a151c059e544fa8c6e67748efe68e#diff-7a02f21c2f0674495c4ff66ae317d9f6L7420

=> it is labelled for devkitPPC_r33 and devkitPPC_r32 releases

And this is the commit which added it back:
https://github.com/devkitPro/buildscripts/commit/37b381ea1f138f48b911e6aa86df1c1c46052d24#diff-7a02f21c2f0674495c4ff66ae317d9f6R7422

=> it is labelled for devkitPPC_r34 release

I would suggest checking your installation again and make sure you have the latest version from early february.

But anyway, it's better to directly include <sys/stat.h> in project files as it's not really safe to rely on such inclusion flow (which will likely get broken again in future versions of devkitppc) so this commit should fix this last compilation issue definitively : https://github.com/ekeeke/Genesis-Plus-GX/commit/77f1529661c4a2afba9ec8fbaf24bb84bc396e3e

**Comment by Ntemis** [comment]
Very weird tbh my devkitppc installation is not more than a months old and i *should* have the latest using the official pacman package installation.
Will try to use pacman to see if any updates are available in a few hours ~14h
Will let you know asap i have any update.

**Comment by Ntemis** [comment]
Update:
Bingo! 
You nailed it!
Packages (11) devkitARM-r52-1  devkitPPC-r35-1  devkitppc-rules-1.0.0-1
              libfat-ogc-1.1.3-2  libogc-1.8.22-1  ppc-bzip2-1.0.6-2
              ppc-libgd-2.2.5-2  ppc-libjpeg-turbo-1.5.3-4
              ppc-libvorbisidec-1.2.1-2  ppc-mxml-2.11-2
              wii-examples-20190201-1
Thank you for your time to investigate this issue! U rock!
