### ISSUE TITLE
Mortal Kombat (Sega CD) hangs while loading

### ISSUE THREAD

**Issue by KamiLordus** [ekeeke/Genesis-Plus-GX#533]
The game works properly until you defeat the first opponent on the arcade ladder. When the game tries to load the next stage/opponet, a black screen appears and the game hangs.
It also happens that you can only select the character you want to fight and the game will not load the first fight.
The latest patch is probably to blame, because I was playing recently (3-4 weeks ago) and there was no problem.

Win 11
Retroarch 1.16
Genesis core latest
Mortal Kombat Sega CD - usa chd format.

Edit:
I tested the Pal versions - MEGA CD (chd file format) and the same situation.

**Comment by ekeeke** [comment]
Fixed in https://github.com/ekeeke/Genesis-Plus-GX/commit/9f25226536df65d32abc327c9f06ee6f625e6828

For the record, it was indeed a regression introduced by previous commit adding emulation of SUB-CPU lock in case of Word-RAM access while it is allocated to Main-CPU. The initial implementation was very basic (it would simply halt SUB-CPU at the end of instruction execution then reexecute the instruction when Word-RAM is reallocated to SUB-CPU) but was not robust to some edge cases like, for example, when the same address register is used as source address for a read then updated with the result of the read (MOVEA (Ax),Ax instruction), which is what Mortal Kombat is doing (with Ax pointing to Word RAM) after allocating Word-RAM to MAIN-CPU. The implemented solution fixes this by saving/restoring address registers state when the locking access is done and also take care of potential address registers post-increment or pre-decrement that could have happened during instruction processing before the access. It's probably a little over-engineered as games will likely mostly use MOVE or MOVEA instructions to access Word-RAM but this way it should be robust to all kind of instructions and is still more efficient than saving all address registers before each executed instruction.

**Comment by KamiLordus** [comment]
Thank you very much for the fix.

**Comment by Tasosgemah** [comment]
@ekeeke 

The game still hangs if you let it's demo/attract mode for a while. It shows the intro video and a couple of demos and then gets stuck to a black screen.
